# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53c5beb1a78b39e36fb000bb8fa96c985027691cfb02839d6522208df2d444dbfeef04b1b9db4b01e582be0a9019326485d6ad841d90e8d7f3734ec41907a55

test:
  secret_key_base: 6dc812e41e61ebdbd1b650e485f3f20c83827d3f969b92c41d8d84aca4c70bdb05230ee505d5768c280fd1caf778c5395446f5ea04bf374a31cb6f7754e0ce83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
